site_name: nobrakes
repo_url: https://github.com/jesperpjohansson/nobrakes-dev
theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - toc.integrate
    - search.suggest

  palette:
    - scheme: slate
      primary: light blue
      accent: orange
  font:
    text: Roboto
    code: Fira Code
  
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Usage: usage.md
  - API Reference: api-reference.md
  - Page Reference: page-reference.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            show_root_heading: true
            show_source: false
            show_signature_annotations: false

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

copyright: Copyright &copy; 2025 Jesper Johansson

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jesperpjohansson/nobrakes-dev

extra_css:
  - assets/css/table.css
            