name: Update Badge
description: Run scripts.update_*_badge and push updated README.md

inputs:
  badge-name:
    description: Name of the badge to update
    required: true

runs:
  using: composite
  steps:
    - name: Update ${{ inputs.badge-name }} badge in README.md
      run: python -m scripts.update_${{ inputs.badge-name }}_badge
      shell: bash

    - name: Commit and push README.md
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git diff --cached --quiet || git commit -m "Update ${{ inputs.badge-name }} badge"
        git push
      shell: bash