name: Build Python Package

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build distributions
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: pip

    - name: Upgrade pip and install build tools
      run: |
        python -m pip install --upgrade pip
        python -m pip install build

    - name: Build sdist and wheel
      run: |
        python -m build

    - name: Check distributions with twine
      run: |
        python -m pip install twine
        python -m twine check dist/*

    - name: Test build
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install dist/*.whl pytest pytest-asyncio pytest-cov aiohttp httpx pyyaml
        python -m scripts.test --opargs cov=nobrakes cov-report=json
    
    - name: Update README coverage badge
      run: python -m scripts.update_coverage_badge

    - name: Commit and push updated README
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git diff --cached --quiet || git commit -m "Update coverage badge"
        git push

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/