name: Build

on:
  push:
    branches:
      - main
    paths:
      - 'pyproject.toml'
      - 'nobrakes/**'
      - 'tests/**'
      - '.github/workflows/build.yml'
      - '.github/actions/set-up-python-env/action.yml'
  workflow_dispatch:

jobs:
  build-dist:
    name: Build and check distributions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set Up Python Environment
        uses: ./.github/actions/set-up-python-env
      
      - name: Install build
        run: |
          python -m pip install build

      - name: Build distributions
        run: |
          python -m build

      - name: Install Twine
        run: |
          python -m pip install twine

      - name: Check distributions
        run: |
          python -m twine check dist/*
      
      - name: Upload distributions artifact
        uses: actions/upload-artifact@v4
        with:
          name: distributions
          path: dist/
      
  test-cov-wheel:
    name: Test wheel distribution with coverage
    needs: build-dist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set Up Python Environment
        uses: ./.github/actions/set-up-python-env
      
      - name: Download distributions artifact
        uses: actions/download-artifact@v4
        with:
          name: distributions
          path: dist/

      - name: Install dependencies
        run: |
          python -m pip install dist/*.whl
          python -m pip install -r requirements/covreport.txt

      - name: Run scripts.covreport
        run: |
          python -m scripts.covreport xml
      
      - name: Debug current directory and files
        run: |
          pwd
          ls -la

      - name: Upload coverage report
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
      
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
