name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  call-pre-build-ci-workflow:
    name: Pre-build CI
    uses: ./.github/workflows/pre-build-ci.yml

  build-dist:
    name: Build distributions
    needs: call-pre-build-ci-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          
      - name: Build sdist and wheel
        run: |
          python -m pip install build
          python -m build

      - name: Check distributions with twine
        run: |
          python -m pip install twine
          python -m twine check dist/*
      
      - name: Upload distribution artifact
        uses: actions/upload-artifact@v4
        with:
          name: distributions
          path: dist/
      
  test-cov-wheel:
    name: Test wheel distribution with coverage
    needs: build-dist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      
      - name: Download distribution artifact
        uses: actions/download-artifact@v4
        with:
          name: distributions
          path: dist/

      - name: Install dependencies
        run: |
          python -m pip install dist/*.whl
          python -m pip install -r requirements/covreport.txt

      - name: Run tests and generate coverage
        run: |
          python -m scripts.covreport json

      - name: Upload coverage JSON
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: coverage-json
          path: coverage.json

  update-cov-badge:
    name: Update Coverage Badge
    needs: test-cov-wheel
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      
      - name: Download coverage JSON
        uses: actions/download-artifact@v4
        with:
          name: coverage-json
          path: .

      - name: Update README coverage badge
        run: python -m scripts.update_coverage_badge

      - name: Commit and push updated README
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "Update coverage badge"
          git push