name: Pre-build CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'pyproject.toml'
      - 'nobrakes/**'
      - 'tests/**'
      - 'scripts/**'
      - 'requirements/lint.txt'
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      
      - name: Set Up Python Environment
        uses: ./.github/actions/set-up-python-env

      - name: Install dependencies
        run: python -m pip install -r requirements/lint.txt

      - name: Run scripts.lint
        run: python -m scripts.lint