name: Lint

on:
  push:
    branches:
      - main
    paths:
      - 'pyproject.toml'
      - 'nobrakes/**'
      - 'tests/**'
      - 'scripts/**'
      - 'requirements/lint.txt'
      - '.github/workflows/lint.yml'
      - '.github/actions/set-up-python-env/action.yml'
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      
      - name: Set Up Python Environment
        uses: ./.github/actions/set-up-python-env

      - name: Install dependencies
        run: python -m pip install -r requirements/lint.txt

      - name: Run scripts.lint
        run: python -m scripts.lint