name: Update Python Badge

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - pyproject.toml

jobs:
  update-badge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      
      - name: Set Up Python Environment
        uses: ./.github/actions/set-up-python-env
        with:
          upgrade-pip: 'false'

      - name: Update Python Badge
        uses: ./.github/actions/update-badge
        with:
          badge-name: 'python'